"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Code = { id: string; name: string; code: string; percent_off: number; active: boolean };
export default function DiscountCodesManager({ initialCodes }: { initialCodes: Code[] }) {
  const sb = createClient(); const [codes, setCodes] = useState(initialCodes); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [percent, setPercent] = useState(10); const [error, setError] = useState("");
  async function add() { setError(""); const { data, error } = await sb.from("discount_codes").insert({ name: name.trim(), code: code.trim().toUpperCase(), percent_off: percent }).select().single(); if (error) { setError(error.message); return; } setCodes((items) => [data as Code, ...items]); setName(""); setCode(""); }
  async function toggle(item: Code) { const { error } = await sb.from("discount_codes").update({ active: !item.active }).eq("id", item.id); if (!error) setCodes((items) => items.map((x) => x.id === item.id ? { ...x, active: !x.active } : x)); }
  return <div className="mx-auto max-w-4xl px-4 py-8"><h1 className="text-3xl font-black text-slate-950">Online Discount Codes</h1><p className="mt-2 text-sm text-slate-500">One active code appears in the store banner and applies at checkout.</p><div className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-4"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Campaign name" className="rounded-xl border p-2"/><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="WELCOME" className="rounded-xl border p-2 font-mono"/><input value={percent} onChange={(e) => setPercent(Number(e.target.value))} type="number" min="1" max="100" className="rounded-xl border p-2"/><button onClick={add} className="rounded-xl bg-brand-navy px-4 py-2 font-bold text-white">Create code</button>{error && <p className="text-sm text-rose-700 sm:col-span-4">{error}</p>}</div><div className="mt-5 space-y-2">{codes.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><span><b>{item.name}</b><span className="ml-3 font-mono">{item.code}</span> · {item.percent_off}%</span><button onClick={() => toggle(item)} className="rounded-lg border px-3 py-1 text-sm font-bold">{item.active ? "Active" : "Inactive"}</button></div>)}</div></div>;
}
